const mongoose = require("mongoose");

const draftCVSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Set when this draft was created via "Edit in Builder" on an Application.
    // Lets us short-circuit duplicate edit requests and recover from a dropped
    // connection: if the POST fails after the draft was already created, the
    // frontend can find it by sourceApplicationId instead of creating a duplicate.
    sourceApplicationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Application",
      default: null,
      index: true,
    },
    title: {
      type: String,
      default: "Untitled CV",
    },
    source: {
      type: String,
      enum: ["upload", "scratch", "unknown"],
      default: "unknown",
    },
    exportCount: {
      type: Number,
      default: 0,
    },
    targetJob: {
      title: String,
      description: String, // Context for AI tailoring
    },
    personalInfo: {
      fullName: String,
      email: String,
      phone: String,
      address: String,
      linkedin: String,
      website: String,
    },
    professionalSummary: {
      type: String,
      default: "",
    },
    experience: [
      {
        title: String,
        company: String,
        startDate: String,
        endDate: String,
        isCurrent: Boolean,
        description: String, // Bullet points
      },
    ],
    projects: [
      {
        title: String,
        link: String,
        description: String, // Bullet points
      },
    ],
    education: [
      {
        degree: String,
        school: String,
        graduationDate: String,
        description: String,
      },
    ],
    skills: [
      {
        name: { type: String, required: true },
        category: { type: String, default: "Uncategorized" },
        isAutoGenerated: { type: Boolean, default: false },
      },
    ],
    tailoredFrom: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DraftCV",
    },
    tailoredForJob: {
      title: String,
      company: String,
      externalId: String,
      source: String,
    },
    isComplete: {
      type: Boolean,
      default: false,
    },
    currentStep: {
      type: String,
      default: "target_job", // Store step ID so user can resume where they left off
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("DraftCV", draftCVSchema);
