const mongoose = require("mongoose");

const draftCVSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    // Set when this draft was created via "Edit in Builder" on an Application.
    // Lets us short-circuit duplicate edit requests and recover from a dropped
    // connection: if the POST fails after the draft was already created, the
    // frontend can find it by sourceApplicationId instead of creating a duplicate.
    sourceApplicationId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Application",
      default: null,
      index: true,
    },
    title: {
      type: String,
      default: "Untitled CV",
    },
    source: {
      type: String,
      enum: ["upload", "scratch", "unknown"],
      default: "unknown",
    },
    exportCount: {
      type: Number,
      default: 0,
    },
    targetJob: {
      title: String,
      description: String, // Context for AI tailoring
    },
    personalInfo: {
      fullName: String,
      email: String,
      phone: String,
      address: String,
      linkedin: String,
      website: String,
    },
    professionalSummary: {
      type: String,
      default: "",
    },
    experience: [
      {
        title: String,
        company: String,
        startDate: String,
        endDate: String,
        isCurrent: Boolean,
        description: String, // Bullet points
      },
    ],
    projects: [
      {
        title: String,
        link: String,
        description: String, // Bullet points
      },
    ],
    education: [
      {
        degree: String,
        school: String,
        graduationDate: String,
        description: String,
      },
    ],
    skills: [
      {
        name: { type: String, required: true },
        category: { type: String, default: "Uncategorized" },
        isAutoGenerated: { type: Boolean, default: false },
        // Per-skill interview-prep metadata, populated when AI generates skills.
        // Used by the CV builder ⓘ popover and saved to Application.interviewPrep
        // (or DraftCV.interviewPrep when no application is linked yet).
        evidence: [
          {
            type: { type: String }, // 'experience' | 'education' | 'project'
            refIndex: Number,
            snippet: String,
          },
        ],
        talkingPoint: String,
      },
    ],
    // Interview Prep saved against this CV when the user has no linked job
    // application yet (e.g., editing an uploaded CV or building from scratch
    // before running a job analysis). Same shape as Application.interviewPrep
    // but without job-context fields (jobQuestions / questionsToAsk).
    interviewPrep: {
      isSaved: { type: Boolean, default: false },
      savedAt: { type: Date },
      skillsWithEvidence: [
        {
          name: String,
          category: String,
          evidence: [
            {
              type: { type: String },
              refIndex: Number,
              snippet: String,
            },
          ],
          talkingPoint: String,
        },
      ],
      userNotes: String,
    },
    tailoredFrom: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "DraftCV",
    },
    tailoredForJob: {
      title: String,
      company: String,
      externalId: String,
      source: String,
    },
    isComplete: {
      type: Boolean,
      default: false,
    },
    currentStep: {
      type: String,
      default: "target_job", // Store step ID so user can resume where they left off
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model("DraftCV", draftCVSchema);
