const mongoose = require('mongoose');

const draftCVSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    title: {
        type: String,
        default: 'Untitled CV',
    },
    source: {
        type: String,
        enum: ['upload', 'scratch', 'unknown'],
        default: 'unknown'
    },
    exportCount: {
        type: Number,
        default: 0
    },
    targetJob: {
        title: String,
        description: String, // Context for AI tailoring
    },
    personalInfo: {
        fullName: String,
        email: String,
        phone: String,
        address: String,
        linkedin: String,
        website: String,
    },
    professionalSummary: {
        type: String,
        default: '',
    },
    experience: [{
        title: String,
        company: String,
        startDate: String,
        endDate: String,
        isCurrent: Boolean,
        description: String, // Bullet points
    }],
    projects: [{
        title: String,
        link: String,
        description: String, // Bullet points
    }],
    education: [{
        degree: String,
        school: String,
        graduationDate: String,
        description: String,
    }],
    skills: [{
        name: { type: String, required: true },
        category: { type: String, default: 'Uncategorized' },
        isAutoGenerated: { type: Boolean, default: false }
    }],
    isComplete: {
        type: Boolean,
        default: false,
    },
    currentStep: {
        type: String,
        default: 'target_job', // Store step ID so user can resume where they left off
    },
}, {
    timestamps: true,
});

module.exports = mongoose.model('DraftCV', draftCVSchema);
